image:
  file: .gitpod.Dockerfile

tasks:
  - name: Doppler login
    command: |
      printf "\033[3J\033c\033[3J"
      printf '%s\n' "${DOPPLER_TOKEN}" | doppler configure set token --scope "${GITPOD_REPO_ROOT}"
      printf '• %s\n' \
        "To modify ${GITPOD_REPO_ROOT}/BotConfig_tmpl.toml go to ${DOPPLER_URL} and update the `main` branch for development purposes"

  - name: Install deps and enter shell
    command: |
      poetry install
      printf "\033[3J\033c\033[3J"
      printf '• %s\n' \
        'Run this command to start bot:' \
        'doppler run --config main --mount BotConfig.toml --mount-template BotConfig_tmpl.toml -- poetry run python3 -m glu'
      
      poetry shell -q