image:
  file: .gitpod.Dockerfile

tasks:
  - name: Doppler login
    command: |
      printf "\033[3J\033c\033[3J"

       printf '%s\n' "${DOPPLER_TOKEN}" | doppler configure set token --scope "${GITPOD_REPO_ROOT}"

      printf '• %s\n' \
        "To update the values of ${GITPOD_REPO_ROOT}/ProdBotConfig.toml go to ${DOPPLER_URL}"

  - name: Install deps and enter shell
    command: |
      printf "\033[3J\033c\033[3J"
      poetry install
      poetry run $SHELL -ic "printf '• %s\n' 'Run this command to start bot:' 'doppler run --config main --mount BotConfig.toml --mount-template BotConfig_tmpl.toml -- poetry run python3 -m glu'"